Expended menu bar with javascript
Sahar-SE/Portfolio pull request #9
Opened 2022-05-10 09:21 UTC by Elijahdre

# Hamburger menu with JavaScript.

2022-05-10 13:29 UTC, ShadyShawkat requested changes
## Hi Team, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-10 13:29 UTC, ShadyShawkat commented on index.html
>          <li><a href="#">Contact</a></li>
- [ ] Kindly make sure that when the user clicks on the nav links in the mobile menu and in the desktop navigation navbar, the page scrolls to the appropriate section of the page (when the user clicks on "portfolio" in the mobile menu or the desktop navigation bar, the page scrolls to the portfolio section). You can use the `href` property to do so.

- [ ] Currently, when the user opens the mobile menu on mobile view, the nav links on desktop view are hidden, and they stay hidden even after the user closes the mobile menu. (Please fix this behavior)

2022-05-12 06:07 UTC, prolajumokeoni approved these changes
Hi @Ream

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_Check inline comments_
 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-12 06:07 UTC, prolajumokeoni commented on index.html
> +        <li><a href="#contact" onclick="closeNav()">Contact</a></li>
#### OPTIONAL

- [ ] Kindly increase the font size of each of the mobile nav links

2022-05-12 08:01 UTC, merged